apiVersion: v1
kind: Service
metadata:
  labels:
    chart: go-ad-man-1.0.0
  name: ad-man-go-ad-man
  namespace: default
spec:
  clusterIP: 100.67.194.5
  ports:
  - name: go-ad-man
    port: ${GO_AD_PORT}
    protocol: TCP
    targetPort: 6111
  selector:
    app: ad-man-go-ad-man
  sessionAffinity: None
  type: ClusterIP
