name: Buildit ElasticSearch
version: 0.0.1-buildit
description: |
  ElasticSearch Buildit component is a qualified and optimized ElasticSearch Engine
  for Rancher Kubernetes environments.
category: Application
