name: Buildit Nginx Public
version: 0.0.1-buildit
description: |
  Nginx Public Buildit component is a qualified and optimized Nginx instance for externalized communication for the RIG 3.0 networking
  ported from Rancher Kubernetes stack.
category: Application
