name: Buildit Nginx Internal
version: 0.0.1-buildit
description: |
  Nginx Internal Buildit component is a qualified and optimized Nginx instance for internal communication for the RIG 3.0 networking
  ported from Rancher Kubernetes stack.
category: Application
