apiVersion: v1
kind: Service
metadata:
  labels:
    chart: nginx-lego-0.2.0
  name: nginx-pub-nginx-lego-monitoring
  namespace: public
spec:
  clusterIP: 100.70.139.246
  ports:
  - name: vts-stats
    port: 18080
    protocol: TCP
    targetPort: 18080
  selector:
    app: nginx-pub-nginx-lego
  sessionAffinity: None
  type: ClusterIP
