.catalog:
  name: "BuildIt - Dublin Architecture Department Microservices POC Pipeline"
  version: "v1"
  description: "This is a Sampler Microservices Pipeline, Defining some pipelines in the CI infrastructured including Jenkins, Nexus and Sonar."
  uuid: buildit-microservices-pipeline-1
  questions:
    - variable: "JENKINSPORT"
      label: "Jenkins Public Port"
      description: "Port on which to run Jenkins Web Interface (fixed for this ansible level)"
      default: 8080
      required: true
      type: "int"
    - variable: "JENKINSJNLPPORT"
      label: "Jenkins JNLP Port"
      description: "Port on which to run Jenkins JNLP Listener (fixed for this ansible level)"
      default: 50000
      required: true
      type: "int"
    - variable: "SONARPORT"
      label: "SonarQube Public Port"
      description: "Port on which to run SonarQube Web Interface (fixed for this ansible level)"
      default: 9000
      required: true
      type: "int"
    - variable: "NEXUSPORT"
      label: "Nexus Public Port"
      description: "Port on which to run Nexus Web Interface (fixed for this ansible level)"
      default: 9003
      required: true
      type: "int"

sonarqube:
  health_check:
    port: 9000
    interval: 60000
    unhealthy_threshold: 5
    healthy_threshold: 5
    response_timeout: 2000
    request_line: 'GET "/sonar" "HTTP/1.0"'
nexus:
  health_check:
    port: 8081
    interval: 60000
    unhealthy_threshold: 5
    healthy_threshold: 5
    response_timeout: 2000
    request_line: 'GET "/nexus/service/local/status" "HTTP/1.0"'
jenkins:
  health_check:
    port: 8080
    interval: 60000
    unhealthy_threshold: 5
    healthy_threshold: 5
    response_timeout: 2000
    request_line: 'GET "/" "HTTP/1.0"'
