apiVersion: v1
kind: Service
metadata:
  labels:
    chart: openvpn-1.0.0
  name: openvpn-openvpn
  namespace: default
spec:
  clusterIP: 100.66.26.82
  ports:
  - name: openvpn
    nodePort: 31458
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: openvpn-openvpn
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a6fab72e20f6111e7ad030a31f40c1a5-2051985363.ap-northeast-1.elb.amazonaws.com
