.catalog:
    name: Buildit Open VPN
    version: 0.0.1-rancher1
    description: "Buildit Open VPN Access Manager"
    maintainer: "BuildIt"
    questions:
        - variable: "SAMBA_REALM"
          type: "string"
          default: "corp.riglet.io"
          label: "Realm for Samba AC-DC Server"
          description: "Realm for Samba AC-DC Server"
          required: true
        - variable: "SAMBA_LDAP_PORT"
          type: "int"
          default: 389
          label: "LDAP Exposed Port from Samba AC-DC Server"
          description: "LDAP Public Port from Samba AC-DC Server"
          required: true
