name: Buildit Open VPN
version: 0.0.1-buildit
description: |
  Open VPN Buildit component is an Open VPN Controller Service providing remote connectivity
  ported from Rancher Kubernetes stack.
category: Networking
