name: Buildit MogoDb Staging
version: 0.0.1-buildit
description: |
  MogoDb Staging Buildit component is NoSQL database optimized for Eolas/Synapse
  ported from Rancher Kubernetes stack.
category: Database
