apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-03-22T23:14:59Z
  labels:
    chart: samba-ad-dc-0.1.0
  name: ad-dc-samba-ad-dc
  namespace: default
spec:
  clusterIP: 100.65.112.12
  ports:
  - name: ldap
    port: 389
    targetPort: ${SAMBA_LDAP_PORT}
    protocol: TCP
    targetPort: ldap
  - name: dns
    port: 53
    targetPort: ${SAMBA_DNS_PORT}
    protocol: TCP
    targetPort: dns
  selector:
    app: ad-dc-samba-ad-dc
  sessionAffinity: None
  type: ClusterIP
