name: Buildit FluentD ES-DS
version: 0.0.1-buildit
description: |
  FluentD ElasticSearch Deamon-Set Buildit component is a Logging Agent for the ElasticSearch Services
  ported from Rancher Kubernetes stack.
category: System
